INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NoMediaControls

NoMediaControls_FILES = Tweak.x
NoMediaControls_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
